### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by cviviers** [zhenzhel/lift_map_detect#1]
Hi @jinpz,

Thanks for the interesting work.
Do you have any of the pretrained weights available to reproduce some of the CIFAR10 results?

Thanks in advance!

**Comment by zhenzhel** [comment]
Hello! For CIFAR10 we just used the official pretrained checkpoint from https://github.com/yang-song/score_sde_pytorch 
Specifically it should be the CIFAR10 `subvp/cifar10_ddpm_continuous` checkpoint 26. 
Feel free to let us know if you have any additional questions!

**Comment by cviviers** [comment]
Perfect, thanks!
