### ISSUE TITLE
Question Regarding the Config Files

### ISSUE THREAD

**Issue by hyang0129** [zhenzhel/lift_map_detect#2]
I am trying to reproduce the paper's original results, but there are multiple configurations for the cifar10 dataset. 

What are the differences between the default, vp, subvp, and ve configurations?

**Comment by zhenzhel** [comment]
They are different diffusion variants. An in-depth explanation can be found in
> Song, Yang, et al. "Score-based generative modeling through stochastic differential equations." https://arxiv.org/abs/2011.13456

In our paper we used the `subvp/cifar10_ddpm_continuous` configuration, and we took the official pretrained diffusion model weights from  https://github.com/yang-song/score_sde_pytorch (checkpoint 26).

Feel free to let us know if you have any additional questions!
